'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Property as PropertyType } from '@/types/agent'
import { Upload } from 'lucide-react'
import { toast } from 'sonner'
import { addProperty } from '@/app/services/propertyService'

type NewProperty = Omit<
  PropertyType,
  'id' | 'agentId' | 'createdAt' | 'updatedAt' | 'views' | 'inquiries'
>

const AddPropertyPage = () => {
  const router = useRouter()
  const [property, setProperty] = useState<Partial<NewProperty>>({
    title: '',
    description: '',
    price: 0,
    currency: 'USD',
    location: '',
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 100,
    status: 'draft',
    images: [],
  })
  const [uploading, setUploading] = useState(false)

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target
    setProperty({ ...property, [name]: value })
  }

  const handleSelectChange = (name: keyof NewProperty) => (value: string) => {
    setProperty({ ...property, [name]: value })
  }

  const handleNumberChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setProperty({ ...property, [name]: Number(value) })
  }

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    setUploading(true)
    const files = e.target.files

    if (files) {
      const imagePromises = Array.from(files).map((file) => {
        return new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            resolve(reader.result as string);
          };
          reader.onerror = reject;
          reader.readAsDataURL(file);
        });
      });

      try {
        const base64Images = await Promise.all(imagePromises);
        setProperty({
          ...property,
          images: [...(property.images || []), ...base64Images],
        });
      } catch (error) {
        console.error("Error converting images to base64:", error);
      }
    }

    setUploading(false);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // Here you would typically send the data to your backend/API
    const newPropertyData = {
      title: "",
      description: "",
      price: 0,
      currency: "USD",
      location: "",
      bedrooms: 0,
      bathrooms: 0,
      squareFeet: 0,
      status: "active" as "active" | "pending" | "sold" | "draft",
      images: [],
      ...property,
      id: "", // id will be generated by addProperty
      imageUrl:
        property.images && property.images.length > 0
          ? property.images[0]
          : "/placeholder.svg",
    };
    addProperty(newPropertyData);
    toast.success("Property added successfully!");
    router.push("/agent/properties");
  };

  return (
    <div className="container mx-auto p-4 md:p-8">
      <Card>
        <CardHeader>
          <CardTitle>Add New Property</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label htmlFor="title">Property Title</label>
                <Input
                  id="title"
                  name="title"
                  value={property.title}
                  onChange={handleInputChange}
                  placeholder="e.g., Modern Downtown Apartment"
                  required
                />
              </div>
              <div className="space-y-2">
                <label htmlFor="location">Location</label>
                <Input
                  id="location"
                  name="location"
                  value={property.location}
                  onChange={handleInputChange}
                  placeholder="e.g., 123 Main St, New York, NY"
                  required
                />
              </div>
            </div>

            <div className="space-y-2">
              <label htmlFor="description">Description</label>
              <Textarea
                id="description"
                name="description"
                value={property.description}
                onChange={handleInputChange}
                placeholder="Describe the property..."
                rows={5}
              />
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div className="space-y-2">
                <label htmlFor="price">Price</label>
                <Input
                  id="price"
                  name="price"
                  type="number"
                  value={property.price}
                  onChange={handleNumberChange}
                  required
                />
              </div>
              <div className="space-y-2">
                <label htmlFor="currency">Currency</label>
                <Select
                  name="currency"
                  onValueChange={handleSelectChange('currency')}
                  defaultValue={property.currency}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select currency" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="USD">USD</SelectItem>
                    <SelectItem value="EUR">EUR</SelectItem>
                    <SelectItem value="GBP">GBP</SelectItem>
                    <SelectItem value="GHS">GHS</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <label htmlFor="status">Status</label>
                <Select
                  name="status"
                  onValueChange={handleSelectChange('status')}
                  defaultValue={property.status}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="draft">Draft</SelectItem>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="sold">Sold</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div className="space-y-2">
                <label htmlFor="bedrooms">Bedrooms</label>
                <Input
                  id="bedrooms"
                  name="bedrooms"
                  type="number"
                  value={property.bedrooms}
                  onChange={handleNumberChange}
                  min="0"
                />
              </div>
              <div className="space-y-2">
                <label htmlFor="bathrooms">Bathrooms</label>
                <Input
                  id="bathrooms"
                  name="bathrooms"
                  type="number"
                  value={property.bathrooms}
                  onChange={handleNumberChange}
                  min="0"
                />
              </div>
              <div className="space-y-2">
                <label htmlFor="squareFeet">Square Feet</label>
                <Input
                  id="squareFeet"
                  name="squareFeet"
                  type="number"
                  value={property.squareFeet}
                  onChange={handleNumberChange}
                  min="0"
                />
              </div>
            </div>

            <div className="space-y-4">
              <label>Images</label>
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
                <Upload className="mx-auto h-12 w-12 text-gray-400" />
                <label
                  htmlFor="file-upload"
                  className="relative cursor-pointer rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500"
                >
                  <span>Upload files</span>
                  <input
                    id="file-upload"
                    name="file-upload"
                    type="file"
                    className="sr-only"
                    multiple
                    onChange={handleImageUpload}
                    accept="image/*"
                  />
                </label>
                <p className="text-xs text-gray-500">
                  PNG, JPG, GIF up to 10MB
                </p>
                {uploading && <p>Uploading...</p>}
              </div>
              <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4">
                {property.images?.map((img, index) => (
                  <div key={index} className="relative">
                    <Image
                      src={img}
                      alt={`preview ${index}`}
                      className="h-24 w-full object-cover rounded-md"
                      width={100}
                      height={100}
                    />
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end space-x-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => router.back()}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={uploading}>
                {uploading ? 'Saving...' : 'Save Property'}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

export default AddPropertyPage